import importlib.util
import json
import pathlib
import tempfile
import unittest


SCRIPT_PATH = pathlib.Path(__file__).resolve().parents[1] / "scripts" / "research_artifact_smoke.py"
SPEC = importlib.util.spec_from_file_location("research_artifact_smoke", SCRIPT_PATH)
research_artifact_smoke = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(research_artifact_smoke)


class ResearchArtifactSmokeTest(unittest.TestCase):
    def test_summarize_artifacts_passes_saved_json_and_markdown_contract(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "output" / "research" / "research-openai.json"
            markdown_path = pathlib.Path(tmpdir) / "output" / "research" / "research-openai.md"
            json_path.parent.mkdir(parents=True)
            payload = {
                "query": "OpenAI",
                "sources": {
                    "wikipedia": {"success": True},
                    "image:openverse": {"success": True},
                },
                "documents": [{"success": True, "url": "https://example.com"}],
                "images": [
                    {
                        "image_url": "https://example.com/openverse.jpg",
                        "source": "image:openverse",
                        "license": "by-sa",
                        "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
                        "attribution": "Image by Example Creator, CC BY-SA 4.0",
                        "license_verification_required": True,
                    }
                ],
                "source_errors": [],
                "artifact": {"format": "json", "path": str(json_path)},
                "brief": {
                    "content": "# Research Brief: OpenAI",
                    "artifact": {"format": "markdown", "path": str(markdown_path)},
                },
            }
            json_path.write_text(json.dumps(payload), encoding="utf-8")
            markdown_path.write_text(
                "\n".join(
                    [
                        "---",
                        "type: argus-research-brief",
                        "---",
                        "",
                        "# Research Brief: OpenAI",
                        "",
                        "## Key Sources",
                        "",
                        "A readable brief body with enough detail to satisfy the artifact smoke checks. "
                        "It includes summary text, source context, and enough characters for archive review.",
                        "",
                        "## Image Candidates",
                        "",
                        "- [Openverse image](https://example.com/openverse.jpg)",
                        "  - Attribution: Image by Example Creator, CC BY-SA 4.0",
                        "  - Verify license metadata and attribution requirements before use.",
                        "",
                        "_Generated by Argus research_workflow._",
                    ]
                ),
                encoding="utf-8",
            )
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(
                result,
                tmpdir,
                require_openverse=True,
            )

            self.assertTrue(summary["passed"])
            self.assertEqual(summary["paths"]["json"], "output/research/research-openai.json")
            self.assertEqual(summary["counts"]["successful_documents"], 1)
            self.assertEqual(summary["counts"]["openverse_images"], 1)
            self.assertEqual(summary["counts"]["openverse_license_complete"], 1)
            self.assertEqual(summary["counts"]["license_verification_required_images"], 1)
            self.assertTrue(summary["checks"]["markdown_has_key_sources"])

    def test_summarize_artifacts_fails_incomplete_openverse_license_contract(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "research.json"
            markdown_path = pathlib.Path(tmpdir) / "research.md"
            payload = {
                "query": "OpenAI",
                "sources": {"wikipedia": {}, "image:openverse": {}},
                "documents": [{"success": True}],
                "images": [
                    {
                        "image_url": "https://example.com/openverse.jpg",
                        "source": "image:openverse",
                        "license": "by-sa",
                        "license_verification_required": True,
                    }
                ],
                "source_errors": [],
                "brief": {"content": "# Research Brief: OpenAI"},
            }
            json_path.write_text(json.dumps(payload), encoding="utf-8")
            markdown_path.write_text(
                "---\ntype: argus-research-brief\n---\n# Research Brief: OpenAI\n## Key Sources\n"
                + ("body " * 60)
                + "\n## Image Candidates\nAttribution: unknown\nVerify license metadata\n"
                + "_Generated by Argus research_workflow._",
                encoding="utf-8",
            )
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(
                result,
                tmpdir,
                require_openverse=True,
            )

            self.assertFalse(summary["passed"])
            self.assertFalse(summary["checks"]["json_openverse_license_complete"])

    def test_summarize_artifacts_fails_when_markdown_lacks_key_sources(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "research.json"
            markdown_path = pathlib.Path(tmpdir) / "research.md"
            payload = {
                "query": "OpenAI",
                "sources": {},
                "documents": [{"success": True}],
                "source_errors": [],
                "brief": {"content": "# Research Brief: OpenAI"},
            }
            json_path.write_text(json.dumps(payload), encoding="utf-8")
            markdown_path.write_text("---\ntype: argus-research-brief\n---\n# Research Brief: OpenAI\n", encoding="utf-8")
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(result, tmpdir)

            self.assertFalse(summary["passed"])
            self.assertFalse(summary["checks"]["markdown_has_key_sources"])

    def test_summarize_artifacts_fails_for_invalid_json_file(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "research.json"
            markdown_path = pathlib.Path(tmpdir) / "research.md"
            json_path.write_text("{not json", encoding="utf-8")
            markdown_path.write_text(
                "---\ntype: argus-research-brief\n---\n# Research Brief: OpenAI\n## Key Sources\n"
                + ("body " * 60)
                + "\n_Generated by Argus research_workflow._",
                encoding="utf-8",
            )
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(result, tmpdir)

            self.assertFalse(summary["passed"])
            self.assertFalse(summary["checks"]["json_parseable"])
            self.assertEqual(summary["errors"]["json"]["code"], "JSONDecodeError")

    def test_smoke_passed_uses_artifact_summary(self):
        self.assertTrue(
            research_artifact_smoke.smoke_passed({"artifacts": {"passed": True}, "review": {"passed": True}})
        )
        self.assertFalse(
            research_artifact_smoke.smoke_passed({"artifacts": {"passed": True}, "review": {"passed": False}})
        )

    def test_summarize_handoff_review_requires_direct_path_match(self):
        workflow_result = {
            "data": {
                "handoff": {
                    "ready": True,
                    "artifact_path": "output/research/research-openai.json",
                    "openverse_image_count": 1,
                    "openverse_license_complete_count": 1,
                    "license_verification_required_count": 1,
                    "license_warnings": ["openverse_license_verification_required"],
                }
            }
        }
        review_result = {
            "success": True,
            "data": {
                "quality_status": "ready",
                "score": 100,
                "warnings": [],
                "license_warnings": ["openverse_license_verification_required"],
                "counts": {
                    "openverse_images": 1,
                    "openverse_license_complete": 1,
                    "license_verification_required_images": 1,
                },
                "handoff": {
                    "schema": "argus.research.review.handoff.v1",
                    "artifact_path": "output/research/research-openai.json",
                    "openverse_image_count": 1,
                    "openverse_license_complete_count": 1,
                    "license_verification_required_count": 1,
                    "license_warnings": ["openverse_license_verification_required"],
                },
            },
        }

        summary = research_artifact_smoke.summarize_handoff_review(
            workflow_result,
            review_result,
            require_openverse=True,
        )

        self.assertTrue(summary["passed"])
        self.assertEqual(summary["score"], 100)
        self.assertEqual(summary["license_counts"]["review_openverse_images"], 1)

        review_result["data"]["counts"]["openverse_images"] = 0
        mismatch = research_artifact_smoke.summarize_handoff_review(
            workflow_result,
            review_result,
            require_openverse=True,
        )
        self.assertFalse(mismatch["passed"])
        self.assertFalse(mismatch["checks"]["review_counts_match_workflow"])

    def test_exit_code_distinguishes_unavailable_from_artifact_failure(self):
        self.assertEqual(
            research_artifact_smoke.exit_code_for_summary({"passed": False, "status": "unavailable"}),
            2,
        )
        self.assertEqual(
            research_artifact_smoke.exit_code_for_summary({"passed": False, "status": "ran"}),
            3,
        )


if __name__ == "__main__":
    unittest.main()
