import importlib.util
import json
import pathlib
import tempfile
import unittest


SCRIPT_PATH = pathlib.Path(__file__).resolve().parents[1] / "scripts" / "research_artifact_smoke.py"
SPEC = importlib.util.spec_from_file_location("research_artifact_smoke", SCRIPT_PATH)
research_artifact_smoke = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(research_artifact_smoke)


class ResearchArtifactSmokeTest(unittest.TestCase):
    def test_summarize_artifacts_passes_saved_json_and_markdown_contract(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "output" / "research" / "research-openai.json"
            markdown_path = pathlib.Path(tmpdir) / "output" / "research" / "research-openai.md"
            json_path.parent.mkdir(parents=True)
            payload = {
                "query": "OpenAI",
                "sources": {"wikipedia": {"success": True}},
                "documents": [{"success": True, "url": "https://example.com"}],
                "images": [],
                "source_errors": [],
                "artifact": {"format": "json", "path": str(json_path)},
                "brief": {
                    "content": "# Research Brief: OpenAI",
                    "artifact": {"format": "markdown", "path": str(markdown_path)},
                },
            }
            json_path.write_text(json.dumps(payload), encoding="utf-8")
            markdown_path.write_text(
                "\n".join(
                    [
                        "---",
                        "type: argus-research-brief",
                        "---",
                        "",
                        "# Research Brief: OpenAI",
                        "",
                        "## Key Sources",
                        "",
                        "A readable brief body with enough detail to satisfy the artifact smoke checks. "
                        "It includes summary text, source context, and enough characters for archive review.",
                        "",
                        "_Generated by Argus research_workflow._",
                    ]
                ),
                encoding="utf-8",
            )
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(result, tmpdir)

            self.assertTrue(summary["passed"])
            self.assertEqual(summary["paths"]["json"], "output/research/research-openai.json")
            self.assertEqual(summary["counts"]["successful_documents"], 1)
            self.assertTrue(summary["checks"]["markdown_has_key_sources"])

    def test_summarize_artifacts_fails_when_markdown_lacks_key_sources(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "research.json"
            markdown_path = pathlib.Path(tmpdir) / "research.md"
            payload = {
                "query": "OpenAI",
                "sources": {},
                "documents": [{"success": True}],
                "source_errors": [],
                "brief": {"content": "# Research Brief: OpenAI"},
            }
            json_path.write_text(json.dumps(payload), encoding="utf-8")
            markdown_path.write_text("---\ntype: argus-research-brief\n---\n# Research Brief: OpenAI\n", encoding="utf-8")
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(result, tmpdir)

            self.assertFalse(summary["passed"])
            self.assertFalse(summary["checks"]["markdown_has_key_sources"])

    def test_summarize_artifacts_fails_for_invalid_json_file(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = pathlib.Path(tmpdir) / "research.json"
            markdown_path = pathlib.Path(tmpdir) / "research.md"
            json_path.write_text("{not json", encoding="utf-8")
            markdown_path.write_text(
                "---\ntype: argus-research-brief\n---\n# Research Brief: OpenAI\n## Key Sources\n"
                + ("body " * 60)
                + "\n_Generated by Argus research_workflow._",
                encoding="utf-8",
            )
            result = {
                "success": True,
                "summary": {"saved": True, "brief_saved": True},
                "data": {
                    "artifact": {"format": "json", "path": str(json_path)},
                    "brief": {"artifact": {"format": "markdown", "path": str(markdown_path)}},
                },
            }

            summary = research_artifact_smoke.summarize_artifacts(result, tmpdir)

            self.assertFalse(summary["passed"])
            self.assertFalse(summary["checks"]["json_parseable"])
            self.assertEqual(summary["errors"]["json"]["code"], "JSONDecodeError")

    def test_smoke_passed_uses_artifact_summary(self):
        self.assertTrue(research_artifact_smoke.smoke_passed({"artifacts": {"passed": True}}))
        self.assertFalse(research_artifact_smoke.smoke_passed({"artifacts": {"passed": False}}))

    def test_exit_code_distinguishes_unavailable_from_artifact_failure(self):
        self.assertEqual(
            research_artifact_smoke.exit_code_for_summary({"passed": False, "status": "unavailable"}),
            2,
        )
        self.assertEqual(
            research_artifact_smoke.exit_code_for_summary({"passed": False, "status": "ran"}),
            3,
        )


if __name__ == "__main__":
    unittest.main()
