#!/usr/bin/env python3
"""Run a saved-artifact quality smoke for Research Toolkit workflows."""

import argparse
import json
import os
import sys
from typing import Any, Dict, Optional


MIN_MARKDOWN_CHARS = 200


def summarize_artifacts(result: Dict[str, Any], project_root: str, require_openverse: bool = False) -> Dict[str, Any]:
    data = result.get("data") or {}
    summary = result.get("summary") or {}
    artifact = data.get("artifact") or {}
    brief = data.get("brief") or {}
    brief_artifact = brief.get("artifact") or {}

    json_path = artifact.get("path")
    markdown_path = brief_artifact.get("path")
    json_payload, json_error = _load_json_file(json_path)
    markdown_content, markdown_error = _load_text_file(markdown_path)
    images = (json_payload or {}).get("images") or []
    openverse_images = [
        image for image in images
        if isinstance(image, dict) and image.get("source") == "image:openverse"
    ]
    complete_license_count = sum(
        1 for image in openverse_images
        if all(image.get(field) for field in ("license", "license_url", "attribution"))
    )
    verification_required_count = sum(1 for image in openverse_images if image.get("license_verification_required") is True)

    checks = {
        "workflow_success": bool(result.get("success")),
        "summary_saved": bool(summary.get("saved")),
        "summary_brief_saved": bool(summary.get("brief_saved")),
        "json_artifact_metadata": artifact.get("format") == "json" and bool(json_path),
        "markdown_artifact_metadata": brief_artifact.get("format") == "markdown" and bool(markdown_path),
        "json_path_inside_project": _path_inside_project(json_path, project_root),
        "markdown_path_inside_project": _path_inside_project(markdown_path, project_root),
        "json_file_exists": bool(json_path and os.path.exists(json_path)),
        "markdown_file_exists": bool(markdown_path and os.path.exists(markdown_path)),
        "json_parseable": isinstance(json_payload, dict),
        "json_has_query": bool((json_payload or {}).get("query")),
        "json_has_sources": isinstance((json_payload or {}).get("sources"), dict),
        "json_has_documents": bool((json_payload or {}).get("documents")),
        "json_has_successful_document": any(
            document.get("success") for document in ((json_payload or {}).get("documents") or [])
        ),
        "json_has_brief_content": bool(((json_payload or {}).get("brief") or {}).get("content")),
        "markdown_min_length": len(markdown_content or "") >= MIN_MARKDOWN_CHARS,
        "markdown_has_frontmatter": str(markdown_content or "").startswith("---\n"),
        "markdown_has_research_type": "type: argus-research-brief" in str(markdown_content or ""),
        "markdown_has_title": "# Research Brief:" in str(markdown_content or ""),
        "markdown_has_key_sources": "## Key Sources" in str(markdown_content or ""),
        "markdown_has_generated_marker": "_Generated by Argus research_workflow._" in str(markdown_content or ""),
        "json_has_openverse_image": not require_openverse or bool(openverse_images),
        "json_openverse_license_complete": not require_openverse
        or complete_license_count == len(openverse_images),
        "json_openverse_verification_required": not require_openverse
        or verification_required_count == len(openverse_images),
        "markdown_has_openverse_license_notice": not require_openverse
        or all(
            marker in str(markdown_content or "")
            for marker in ("## Image Candidates", "Attribution:", "Verify license metadata")
        ),
    }
    return {
        "success": bool(result.get("success")),
        "passed": all(checks.values()),
        "checks": checks,
        "paths": {
            "json": _relative_path(json_path, project_root),
            "markdown": _relative_path(markdown_path, project_root),
        },
        "counts": {
            "documents": len((json_payload or {}).get("documents") or []),
            "successful_documents": sum(
                1 for document in ((json_payload or {}).get("documents") or []) if document.get("success")
            ),
            "images": len(images),
            "openverse_images": len(openverse_images),
            "openverse_license_complete": complete_license_count,
            "license_verification_required_images": verification_required_count,
            "source_errors": len((json_payload or {}).get("source_errors") or []),
            "markdown_chars": len(markdown_content or ""),
        },
        "errors": {
            "top_level": result.get("error") or {},
            "json": json_error,
            "markdown": markdown_error,
        },
    }


def smoke_passed(summary: Dict[str, Any]) -> bool:
    artifact_summary = summary.get("artifacts") or {}
    review_summary = summary.get("review") or {}
    return bool(artifact_summary.get("passed") and review_summary.get("passed"))


def summarize_handoff_review(workflow_result: Dict[str, Any], review_result: Dict[str, Any], require_openverse: bool = False) -> Dict[str, Any]:
    workflow_handoff = ((workflow_result.get("data") or {}).get("handoff") or {})
    review_data = review_result.get("data") or {}
    review_handoff = review_data.get("handoff") or {}
    review_counts = review_data.get("counts") or {}
    review_license_warnings = review_data.get("license_warnings") or []
    checks = {
        "workflow_handoff_ready": bool(workflow_handoff.get("ready")),
        "workflow_handoff_has_artifact": bool(workflow_handoff.get("artifact_path")),
        "review_success": bool(review_result.get("success")),
        "review_handoff_schema": review_handoff.get("schema") == "argus.research.review.handoff.v1",
        "review_path_matches_workflow": review_handoff.get("artifact_path") == workflow_handoff.get("artifact_path"),
        "review_quality_ready": review_data.get("quality_status") == "ready",
    }
    if require_openverse:
        workflow_license_counts = (
            workflow_handoff.get("openverse_image_count", 0),
            workflow_handoff.get("openverse_license_complete_count", 0),
            workflow_handoff.get("license_verification_required_count", 0),
        )
        review_license_counts = (
            review_counts.get("openverse_images", 0),
            review_counts.get("openverse_license_complete", 0),
            review_counts.get("license_verification_required_images", 0),
        )
        review_handoff_counts = (
            review_handoff.get("openverse_image_count", 0),
            review_handoff.get("openverse_license_complete_count", 0),
            review_handoff.get("license_verification_required_count", 0),
        )
        openverse_count = workflow_license_counts[0]
        checks.update(
            {
                "workflow_handoff_has_openverse": openverse_count > 0,
                "workflow_handoff_license_complete": workflow_license_counts[1] == openverse_count,
                "workflow_handoff_verification_required": workflow_license_counts[2] == openverse_count,
                "workflow_handoff_license_warning": "openverse_license_verification_required"
                in (workflow_handoff.get("license_warnings") or []),
                "review_counts_match_workflow": review_license_counts == workflow_license_counts,
                "review_license_warning": "openverse_license_verification_required"
                in review_license_warnings,
                "review_handoff_counts_match": review_handoff_counts == review_license_counts,
                "review_handoff_license_warning": review_handoff.get("license_warnings")
                == review_license_warnings,
            }
        )
    return {
        "passed": all(checks.values()),
        "checks": checks,
        "quality_status": review_data.get("quality_status"),
        "score": review_data.get("score"),
        "warnings": review_data.get("warnings") or [],
        "license_warnings": review_license_warnings,
        "license_counts": {
            "workflow_openverse_images": workflow_handoff.get("openverse_image_count", 0),
            "review_openverse_images": review_counts.get("openverse_images", 0),
            "review_openverse_license_complete": review_counts.get("openverse_license_complete", 0),
            "review_verification_required": review_counts.get("license_verification_required_images", 0),
        },
        "handoff": review_handoff,
        "error": review_result.get("error") or {},
    }


def exit_code_for_summary(summary: Dict[str, Any]) -> int:
    if summary.get("passed"):
        return 0
    if summary.get("status") == "unavailable":
        return 2
    return 3


def run_smoke(args: argparse.Namespace) -> int:
    try:
        from argus_server.server import _get_tools
    except Exception as ex:
        summary = {
            "success": False,
            "passed": False,
            "status": "unavailable",
            "tool_error": {
                "code": "TOOL_IMPORT_ERROR",
                "message": f"Research tools could not be imported: {ex}",
            },
        }
        print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
        return 2

    project_root = os.getcwd()
    research = _get_tools()["research"]
    sources = args.source or ["wikipedia"]
    require_openverse = "image:openverse" in sources
    result = research.research_workflow(
        args.query,
        sources=sources,
        limit=args.limit,
        timeout=args.timeout,
        max_chars_per_page=args.max_chars_per_page,
        images_per_page=args.images_per_page,
        render_js=False,
        retries=args.retries,
        include_brief=True,
        save=True,
        save_brief=True,
        output_dir=args.output_dir,
    )
    review_result = research.research_review_artifact(
        handoff=((result.get("data") or {}).get("handoff") or {}),
    )
    summary = {
        "success": False,
        "passed": False,
        "status": "ran",
        "query": args.query,
        "sources": sources,
        "openverse_required": require_openverse,
        "output_dir": args.output_dir,
        "artifacts": summarize_artifacts(result, project_root, require_openverse),
        "review": summarize_handoff_review(result, review_result, require_openverse),
    }
    summary["passed"] = smoke_passed(summary)
    summary["success"] = summary["passed"]
    summary["exit_code"] = exit_code_for_summary(summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    return summary["exit_code"]


def _load_json_file(path: Optional[str]) -> tuple:
    if not path:
        return None, {"code": "MISSING_PATH", "message": "JSON artifact path is missing"}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle), {}
    except (OSError, json.JSONDecodeError) as ex:
        return None, {"code": ex.__class__.__name__, "message": str(ex)}


def _load_text_file(path: Optional[str]) -> tuple:
    if not path:
        return "", {"code": "MISSING_PATH", "message": "Markdown artifact path is missing"}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read(), {}
    except OSError as ex:
        return "", {"code": ex.__class__.__name__, "message": str(ex)}


def _path_inside_project(path: Optional[str], project_root: str) -> bool:
    return _resolve_project_path(path, project_root) is not None


def _relative_path(path: Optional[str], project_root: str) -> Optional[str]:
    resolved = _resolve_project_path(path, project_root)
    if not resolved:
        return None
    return os.path.relpath(
        resolved,
        os.path.realpath(os.path.abspath(project_root)),
    )


def _resolve_project_path(path: Optional[str], project_root: str) -> Optional[str]:
    if not path:
        return None
    root = os.path.realpath(os.path.abspath(project_root))
    candidate = path if os.path.isabs(path) else os.path.join(root, path)
    resolved = os.path.realpath(os.path.abspath(candidate))
    try:
        if os.path.commonpath([root, resolved]) != root:
            return None
    except ValueError:
        return None
    return resolved


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", default="OpenAI", help="Saved workflow smoke query.")
    parser.add_argument("--source", action="append", default=None, help="Repeat with image:openverse to require the license contract.")
    parser.add_argument("--limit", type=int, default=1, help="Workflow page limit.")
    parser.add_argument("--timeout", type=int, default=20, help="Page crawl timeout in seconds.")
    parser.add_argument("--max-chars-per-page", type=int, default=1500, help="Maximum page text characters to keep.")
    parser.add_argument("--images-per-page", type=int, default=5, help="Maximum images to keep per page.")
    parser.add_argument("--retries", type=int, default=1, help="Extra retries for retriable crawl failures.")
    parser.add_argument("--output-dir", default="output/research/artifact-smoke", help="Project-local artifact directory.")
    return parser


def main() -> int:
    return run_smoke(build_parser().parse_args())


if __name__ == "__main__":
    sys.exit(main())
