#!/usr/bin/env python3
"""Run a saved-artifact quality smoke for Research Toolkit workflows."""

import argparse
import json
import os
import sys
from typing import Any, Dict, Optional


MIN_MARKDOWN_CHARS = 200


def summarize_artifacts(result: Dict[str, Any], project_root: str) -> Dict[str, Any]:
    data = result.get("data") or {}
    summary = result.get("summary") or {}
    artifact = data.get("artifact") or {}
    brief = data.get("brief") or {}
    brief_artifact = brief.get("artifact") or {}

    json_path = artifact.get("path")
    markdown_path = brief_artifact.get("path")
    json_payload, json_error = _load_json_file(json_path)
    markdown_content, markdown_error = _load_text_file(markdown_path)

    checks = {
        "workflow_success": bool(result.get("success")),
        "summary_saved": bool(summary.get("saved")),
        "summary_brief_saved": bool(summary.get("brief_saved")),
        "json_artifact_metadata": artifact.get("format") == "json" and bool(json_path),
        "markdown_artifact_metadata": brief_artifact.get("format") == "markdown" and bool(markdown_path),
        "json_path_inside_project": _path_inside_project(json_path, project_root),
        "markdown_path_inside_project": _path_inside_project(markdown_path, project_root),
        "json_file_exists": bool(json_path and os.path.exists(json_path)),
        "markdown_file_exists": bool(markdown_path and os.path.exists(markdown_path)),
        "json_parseable": isinstance(json_payload, dict),
        "json_has_query": bool((json_payload or {}).get("query")),
        "json_has_sources": isinstance((json_payload or {}).get("sources"), dict),
        "json_has_documents": bool((json_payload or {}).get("documents")),
        "json_has_successful_document": any(
            document.get("success") for document in ((json_payload or {}).get("documents") or [])
        ),
        "json_has_brief_content": bool(((json_payload or {}).get("brief") or {}).get("content")),
        "markdown_min_length": len(markdown_content or "") >= MIN_MARKDOWN_CHARS,
        "markdown_has_frontmatter": str(markdown_content or "").startswith("---\n"),
        "markdown_has_research_type": "type: argus-research-brief" in str(markdown_content or ""),
        "markdown_has_title": "# Research Brief:" in str(markdown_content or ""),
        "markdown_has_key_sources": "## Key Sources" in str(markdown_content or ""),
        "markdown_has_generated_marker": "_Generated by Argus research_workflow._" in str(markdown_content or ""),
    }
    return {
        "success": bool(result.get("success")),
        "passed": all(checks.values()),
        "checks": checks,
        "paths": {
            "json": _relative_path(json_path, project_root),
            "markdown": _relative_path(markdown_path, project_root),
        },
        "counts": {
            "documents": len((json_payload or {}).get("documents") or []),
            "successful_documents": sum(
                1 for document in ((json_payload or {}).get("documents") or []) if document.get("success")
            ),
            "images": len((json_payload or {}).get("images") or []),
            "source_errors": len((json_payload or {}).get("source_errors") or []),
            "markdown_chars": len(markdown_content or ""),
        },
        "errors": {
            "top_level": result.get("error") or {},
            "json": json_error,
            "markdown": markdown_error,
        },
    }


def smoke_passed(summary: Dict[str, Any]) -> bool:
    artifact_summary = summary.get("artifacts") or {}
    return bool(artifact_summary.get("passed"))


def exit_code_for_summary(summary: Dict[str, Any]) -> int:
    if summary.get("passed"):
        return 0
    if summary.get("status") == "unavailable":
        return 2
    return 3


def run_smoke(args: argparse.Namespace) -> int:
    try:
        from argus_server.server import _get_tools
    except Exception as ex:
        summary = {
            "success": False,
            "passed": False,
            "status": "unavailable",
            "tool_error": {
                "code": "TOOL_IMPORT_ERROR",
                "message": f"Research tools could not be imported: {ex}",
            },
        }
        print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
        return 2

    project_root = os.getcwd()
    research = _get_tools()["research"]
    sources = args.source or ["wikipedia"]
    result = research.research_workflow(
        args.query,
        sources=sources,
        limit=args.limit,
        timeout=args.timeout,
        max_chars_per_page=args.max_chars_per_page,
        images_per_page=args.images_per_page,
        render_js=False,
        retries=args.retries,
        include_brief=True,
        save=True,
        save_brief=True,
        output_dir=args.output_dir,
    )
    summary = {
        "success": False,
        "passed": False,
        "status": "ran",
        "query": args.query,
        "sources": sources,
        "output_dir": args.output_dir,
        "artifacts": summarize_artifacts(result, project_root),
    }
    summary["passed"] = smoke_passed(summary)
    summary["success"] = summary["passed"]
    summary["exit_code"] = exit_code_for_summary(summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    return summary["exit_code"]


def _load_json_file(path: Optional[str]) -> tuple:
    if not path:
        return None, {"code": "MISSING_PATH", "message": "JSON artifact path is missing"}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle), {}
    except (OSError, json.JSONDecodeError) as ex:
        return None, {"code": ex.__class__.__name__, "message": str(ex)}


def _load_text_file(path: Optional[str]) -> tuple:
    if not path:
        return "", {"code": "MISSING_PATH", "message": "Markdown artifact path is missing"}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read(), {}
    except OSError as ex:
        return "", {"code": ex.__class__.__name__, "message": str(ex)}


def _path_inside_project(path: Optional[str], project_root: str) -> bool:
    if not path:
        return False
    try:
        return os.path.commonpath([os.path.abspath(project_root), os.path.abspath(path)]) == os.path.abspath(project_root)
    except ValueError:
        return False


def _relative_path(path: Optional[str], project_root: str) -> Optional[str]:
    if not path:
        return None
    if not _path_inside_project(path, project_root):
        return None
    return os.path.relpath(path, project_root)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", default="OpenAI", help="Saved workflow smoke query.")
    parser.add_argument(
        "--source",
        action="append",
        default=None,
        help="Workflow source. May be passed multiple times. Defaults to wikipedia.",
    )
    parser.add_argument("--limit", type=int, default=1, help="Workflow page limit.")
    parser.add_argument("--timeout", type=int, default=20, help="Page crawl timeout in seconds.")
    parser.add_argument("--max-chars-per-page", type=int, default=1500, help="Maximum page text characters to keep.")
    parser.add_argument("--images-per-page", type=int, default=5, help="Maximum images to keep per page.")
    parser.add_argument("--retries", type=int, default=1, help="Extra retries for retriable crawl failures.")
    parser.add_argument(
        "--output-dir",
        default="output/research/artifact-smoke",
        help="Project-local output directory for the saved JSON and Markdown artifacts.",
    )
    return parser


def main() -> int:
    return run_smoke(build_parser().parse_args())


if __name__ == "__main__":
    sys.exit(main())
