"""Markdown rendering for traceable research comparisons."""

import json
import re
from datetime import datetime, timezone
from typing import Any, Dict
from urllib.parse import urlparse


def render_comparison_brief(report: Dict) -> Dict:
    comparison = report.get("comparison") or {}
    sources = report.get("sources") or []
    lines = [
        "---",
        "type: argus-research-comparison",
        f"focus: {json.dumps(report.get('query') or '', ensure_ascii=False)}",
        f"generated_at: {_utc_timestamp()}",
        f"sources: {len(sources)}",
        f"claims: {comparison.get('claim_count') or 0}",
        "tags: [argus, research-comparison]",
        "---",
        "",
        f"# {_clip(comparison.get('title') or 'Research Comparison', 240)}",
        "",
        "## Overview",
        "",
        _clip(comparison.get("overview"), 4000),
        "",
        "## Sources",
        "",
    ]
    for source in sources:
        label = _markdown_link(source.get("title") or source["source_id"], source.get("url"))
        lines.append(
            f"- `{source['source_id']}` {label} "
            f"(artifact: `{source.get('artifact_path')}`)"
        )
    lines.append("")
    for category, heading in (
        ("agreements", "Agreements"),
        ("differences", "Differences"),
        ("evidence", "Evidence"),
    ):
        lines.extend([f"## {heading}", ""])
        claims = comparison.get(category) or []
        if not claims:
            lines.append("- None identified.")
        for claim in claims:
            citations = ", ".join(f"`{item}`" for item in claim["citations"])
            lines.append(f"- {_clip(claim.get('statement'), 1200)} ({citations})")
        lines.append("")
    lines.extend(["## Open Questions", ""])
    questions = comparison.get("open_questions") or []
    if not questions:
        lines.append("- None identified.")
    else:
        lines.extend(f"- {_clip(question, 600)}" for question in questions)
    lines.extend(["", "---", "_Generated by Argus research_compare_artifacts._"])
    content = "\n".join(lines)
    return {
        "format": "markdown",
        "content": content,
        "artifact": None,
        "source_count": len(sources),
        "claim_count": comparison.get("claim_count") or 0,
        "citation_count": comparison.get("citation_count") or 0,
    }


def _markdown_link(label: Any, url: Any) -> str:
    clean_label = _clean_text(label or url or "untitled").replace("[", "\\[").replace("]", "\\]")
    clean_url = str(url or "").strip()
    parsed = urlparse(clean_url)
    if parsed.scheme in ("http", "https") and parsed.netloc:
        return f"[{clean_label}]({clean_url})"
    return clean_label


def _clip(value: Any, max_chars: int) -> str:
    text = _clean_text(value)
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip() + "..."


def _clean_text(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def _utc_timestamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
